WITH USED_GOODS_BOARD_DONE AS (
    SELECT *
    FROM USED_GOODS_BOARD
    WHERE STATUS = 'DONE'
)
SELECT
    U.USER_ID, U.NICKNAME, SUM(D.PRICE) TOTAL_SALES
FROM
    USED_GOODS_BOARD_DONE D
    LEFT JOIN USED_GOODS_USER U
    ON D.WRITER_ID = U.USER_ID
GROUP BY D.WRITER_ID
HAVING SUM(D.PRICE) >= 700000
ORDER BY TOTAL_SALES ASC;