-- 코드를 입력하세요 
SELECT FLAVOR
FROM (SELECT A.SHIPMENT_ID, A.FLAVOR, A.TOTAL_ORDER, B.INGREDIENT_TYPE
      FROM (FIRST_HALF as A
            JOIN ICECREAM_INFO as B
      ON a.FLAVOR = b.FLAVOR)
      WHERE TOTAL_ORDER > 3000 AND INGREDIENT_TYPE = 'fruit_based') favorite_fruit_based
ORDER BY TOTAL_ORDER DESC;